### ISSUE TITLE
std::sort fails on BitArchiveInfo::items

### ISSUE THREAD

**Issue by fire-eggs** [rikyoz/bit7z#54]
Bit7z V3.1.3
Visual Studio 2019

Thought I'd sort the vector<BitArchiveItem> by filename:
```
bool sortfunc(BitArchiveItem a, BitArchiveItem b) { return a.name() < b.name(); }
...
BitArchiveInfo bai{ lib, path, BitFormat::Rar };
auto arc_items = bai.items();
std::sort(arc_items.begin(), arc_items.end(), sortfunc);
```

but got three of these utterly confusing compile errors:
```
1>E:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\algorithm(7247,25): error C2280: 'bit7z::BitArchiveItem &bit7z::BitArchiveItem::operator =(const bit7z::BitArchiveItem &)': attempting to reference a deleted function
1>E:\proj\DarkThumbs2\DT_Bit7z\bit7z\include\bitarchiveitem.hpp(106): message : compiler has generated 'bit7z::BitArchiveItem::operator =' here
1>E:\proj\DarkThumbs2\DT_Bit7z\bit7z\include\bitarchiveitem.hpp(106,5): message : 'bit7z::BitArchiveItem &bit7z::BitArchiveItem::operator =(const bit7z::BitArchiveItem &)': function was implicitly deleted because 'bit7z::BitArchiveItem' has a data member 'bit7z::BitArchiveItem::mItemIndex' of const-qualified non-class type
1>E:\proj\DarkThumbs2\DT_Bit7z\bit7z\include\bitarchiveitem.hpp(97): message : see declaration of 'bit7z::BitArchiveItem::mItemIndex'
1>E:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\algorithm(7369): message : see reference to function template instantiation '_BidIt *std::_Insertion_sort_unchecked<_RanIt,bool(__cdecl *)(bit7z::BitArchiveItem,bit7z::BitArchiveItem)>(const _BidIt,const _BidIt,_Pr)' being compiled
1>        with
1>        [
1>            _BidIt=bit7z::BitArchiveItem *,
1>            _RanIt=bit7z::BitArchiveItem *,
1>            _Pr=bool (__cdecl *)(bit7z::BitArchiveItem,bit7z::BitArchiveItem)
1>        ]
1>E:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\algorithm(7399): message : see reference to function template instantiation 'void std::_Sort_unchecked<bit7z::BitArchiveItem*,bool(__cdecl *)(bit7z::BitArchiveItem,bit7z::BitArchiveItem)>(_RanIt,_RanIt,__int64,_Pr)' being compiled
1>        with
1>        [
1>            _RanIt=bit7z::BitArchiveItem *,
1>            _Pr=bool (__cdecl *)(bit7z::BitArchiveItem,bit7z::BitArchiveItem)
1>        ]
1>E:\proj\DarkThumbs2\DT_Bit7z\rar.cpp(31): message : see reference to function template instantiation 'void std::sort<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,bool(__cdecl *)(bit7z::BitArchiveItem,bit7z::BitArchiveItem)>(const _RanIt,const _RanIt,_Pr)' being compiled
1>        with
1>        [
1>            _Ty=bit7z::BitArchiveItem,
1>            _RanIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<bit7z::BitArchiveItem>>>,
1>            _Pr=bool (__cdecl *)(bit7z::BitArchiveItem,bit7z::BitArchiveItem)
1>        ]
```

I get the same result even if I create a copy of the items() vector.

Any hints?
Thanks!

**Comment by rikyoz** [comment]
Hi!
Did you try to use a `sortfunc` taking constant reference arguments?
Something like `bool sortfunc(const BitArchiveItem& a, const BitArchiveItem& b) { return a.name() < b.name(); }`.
It should also optimize the operation since you avoid unnecessary copies of the BitArchiveItem objects you compare.

The main reason for the error you're getting is that the `BitArchiveItem` has a `const` member variable (i.e., the item index inside the archive, which doesn't change, hence the const-ness).
This variable disables the generation of an implicit copy constructor, and the class doesn't specify a custom one.
Hence you cannot pass by value a `BitArchiveItem` object to a function like in your `sortfunc`, since it requires the ability to copy the objects. 
Passing by reference should fix the problem.

As a side note, copying `BitArchiveItem`s can be expensive since they contain a `map` of every property it has.

**Comment by fire-eggs** [comment]
Much obliged for the quick response! Alas, I still get the same complaints, with the following sortfunc:
```
bool sortfunc(const BitArchiveItem& a, const BitArchiveItem& b) { return a.name() < b.name(); }
```

[C++ templates make my head hurt ... ]
